### PR TITLE
Provider reference file

### PR DESCRIPTION
**Pull request by shaselton-usds**
Adding a base object `provider_references`. The object has the same attributes as the `provider_groups` with an additional attribute `provider_group_id`. 

Provider_groups can be moved to the `provider_references` object and give a numeric value for the `provider_group_id` attribute. In the `negotiated_rates` object, an array of `provider_group_id` can be stored in `provider_references` to avoid having to repeat the `provider_groups` object if the provider network is too large to continue to repeat for each negotiated rate for each item and service.

The schema for the `provider_references` definition has the possibility, though not currently, to be moved to an external file and referenced there. That would be a possible next iterative step.

### CODE REVIEW

**Comment by tdfow** [comment]
@shaselton-usds so, this pull request is going to make the provider_references object required?  If so, does that mean that there will need to be a reference id generated for each provider group combination that is in the file?

**Comment by shaselton-usds** [comment]
@tdfow Not going to be required to use the `provider_references`. You still may use `provider_groups` if you feel that is best for you. You can take a peek at the requirements here: https://github.com/CMSgov/price-transparency-guide/blob/f9c78aff1dd80d933cf8816e069e02a90c048a5d/schemas/in-network-rates/in-network-rates.json#L197-L200

That said, using `provider_references` will make a significant impact on the size of the files if used. Yes, there will need to be some numeric user generated id to populate the `provider_group_id`
https://github.com/CMSgov/price-transparency-guide/blob/f9c78aff1dd80d933cf8816e069e02a90c048a5d/schemas/in-network-rates/in-network-rates.json#L123-L135

**Comment by garysolebc** [comment]
Would we be able to have the provider reference section as an external file reference.  I say this because one of the areas that likely changes the most from month to month is the list of providers related to their file.  So this could be 'managed' separately from the rest of the INN and OON file.

**Comment by shaselton-usds** [comment]
@garysolebc No external references with this PR.

**Comment by Kvillafor** [comment]
Will the optional provider groups be added to the schema?

**Pull request merged**
