### PR TITLE
Billing class

### PR DESCRIPTION
**Pull request by shaselton-usds**
Introducing `billing_class` contextual attribute to the in-network and allowed-amounts schema to distinguish negotiated rates between "professional" and "institutional" claims.

### CODE REVIEW

**Comment by Vcat1011** [comment]
Just need to confirm; this is a revision to our current schemas.

**Comment by Nio-1** [comment]
Will Service_code still be required to be if the billing_class is "institutional"?  That would not make sense as it is not applicable.  So, will you allow service_code field to be null/blank/space or the type of bill or some other idea like "II" or 'IO"?

**Comment by Ginger228** [comment]
With this update will we define institutional as anyone who bills the carrier via UB-04?  There are examples of skilled nursing that bill via HCFA and some via UB-04.

**Comment by jschmor** [comment]
@Ginger228 - this is an interesting question.
For billing_class - I think it should be defined as the data billing class meaning for ANSII standards as previously suggested.

- Institutional = CMS-1450/UB (paper) and 837/835i
- Professional = CMS-1500 (paper) and 837/835p

 However, while CMS would define HH, SNF, Freestanding dialysis centers, ASC, etc as using the institutional form - they may categorize these provider types as non-institutional. And in my experience - healthplans, and even state Medicaid and other government programs may even contractually obligate these provider types to bill on the professional form or using professional EDI layouts. 

So is billing_class defined as the form or edi format or by the provider type? Not sure that I understand enough yet to see how this plays out with the entire structure - but I would agree that it might cause issues with comparing some of these other provider types because some payors will call them institutional and some will call them professional.

**Comment by tdfow** [comment]
my assumption for those plans that have dental as part of their medical plan that the billing_class for these items/services would be associated with 'Professional'?  
Also, for an item/service, such as DME, with applicable rates for both Professional and Institutional, then there would be both  business_class entries noted for the specific rates/providers

**Comment by jschmor** [comment]
@tdfow - I think I am perhaps confused. If billing_class is defined by the claim type alone I think this could get confused by the fact that some payors mandate different forms for different provider types vs the actual provider type.

Example:
Payor A: Requires HH services to be billed on an institutional claim form/format and rates are set by the HHRG and tied to the rev code. _Payor A would report the billing_class for the HH provider as Institutional._

Payor B: Requires the same provider to bill HH services to be billed on a professional claim form/format with rates set FFS by the CPT code. _Payor B would report the billing_class for the HH provider as Professional._

While neither plan individually might have a problem reporting out the billing_class - the definition of the form/format alone may not accurately describe the provider type. Perhaps this is not an issue in that the provider is classified differently?

**Comment by tdfow** [comment]
@jschmor Since the product rates are identified by product for a given provider, I would think the business class would have to align the rates for the provider.

**Comment by Ginger228** [comment]
> my assumption for those plans that have dental as part of their medical plan that the billing_class for these items/services would be associated with 'Professional'? Also, for an item/service, such as DME, with applicable rates for both Professional and Institutional, then there would be both business_class entries noted for the specific rates/providers

I agree with the statement regarding dental.  They should be professional.  Not sure about DME- typically DME is billed as professional using HCPC or CPT as the billing codes.  When billed by an institution the billing code is both a revenue code and the corresponding CPT/HCPC.  
Institutional example: Hospital A DME of crutches billing code 029X (revenue code) and E0114 (HCPC).  837I  billing type = 131 (outpatient) 
Professional example: Supply Store billing code E0114  837P place of service = 01

**Comment by shaselton-usds** [comment]
@Nio-1 The schema is defined as `service_code` being required for the `billing_class` of "professional". Otherwise it is optional.

**Comment by shaselton-usds** [comment]
@Ginger228 - do you have negotiated rates set up for items and services that would be "institutional" for the `billing_class`? Those rates are what would be reported. Same goes for professional and the various service_codes associated with the negotiated rate.

**Pull request merged**
