### PR TITLE
Percentage added to negotiated_type

### PR DESCRIPTION
**Pull request by shaselton-usds**
Adding support for reporting negotiations that are based on a percentage vs a dollar amount. A common contractual arrangement would be "percentage of billed" charges.

Additional optional attributes to be considered after this PR related to percentage:
* relative priority
* not-to-exceed thresholds
* hurdle thresholds

### CODE REVIEW

**Comment by shaselton-usds** [comment]
An example for a service that is contracted with a 35.7% of billed charges within the `negotiated_price` object.

```json
{
  "negotiated_type": "percentage",
  "negotiated_rate": 37.5,
  "expiration_date": "2022-01-01",
  "billing_class": "institutional"
}
```

**Comment by CMS-to-the-max** [comment]
test

**Comment by Ginger228** [comment]
> An example for a service that is contracted with a 35.7% of billed charges within the `negotiated_price` object.
> 
> ```json
> {
>   "negotiated_type": "percentage",
>   "negotiated_rate": 37.5,
>   "expiration_date": "2022-01-01",
>   "billing_class": "institutional"
> }
> ```

Thanks for this @shaselton-usds  

QQ would this also apply to payment methods for the Average Wholesale Price? This is typically how carriers are paying for infusion therapy, claims are adjudicated by going back to see the wholesale price at the time of service and paying a percentage.

**Comment by taylorpatriciab** [comment]
@shaselton-usds Thank  you for defining this.  Would you consider defining a negotiated_type value of 'per diem' with the per diem rates to be provided in the negotiated_rate?

**Comment by jsalashkar** [comment]
> Adding support for reporting negotiations that are based on a percentage vs a dollar amount. A common contractual arrangement would be "percentage of billed" charges.
> 
> Additional optional attributes to be considered after this PR related to percentage:
> 
> * relative priority
> * not-to-exceed thresholds
> * hurdle thresholds

Thank you for the update.  This certainly can be useful in some scenarios where we may only be able to provide a contractual percentage, but no rate to go with it (i.e. we either have a rate OR a percentage to share).

We often face a scenario where the provider/facility has a rate, but also has a negotiated percentage or weight that is applied to the 'base' rate.  Would it be possible to somehow align both a rate AND a percentage/weight within the same negotiated rate object?

This may sound trivial, but this enhancement would prevent the need to 'scale' rates prior to producing MRFs to all possible contractual variations of the base rate - we could use the same single set of base rates and simply couple it with the percentage/weight as needed within the MRF itself.  This can drastically reduce the amount of data and processing time needed within the processes.

**Comment by jltang-kp** [comment]
@jsalashkar See post https://github.com/CMSgov/price-transparency-guide/pull/395

It looks like there will be an additional text field under the negotiated price object, thiswill most likely needed to be used to differentiate percent of billed amount or another amount like medicare rates and percentage.

**Comment by shaselton-usds** [comment]
@jltang-kp The additional text field is not to be used in the differentiation of percentage arrangements like you've described.  Reference-based pricing that you've described ***must*** be disclosed as a dollar amount by using whatever percentage multipled by what ever the based price that is being referenced. 

You can find further information in the final rule [here](https://www.federalregister.gov/d/2020-24591/p-647)

**Comment by shaselton-usds** [comment]
@Ginger228 Do you know what the AWP number is when building out these files on a monthly cadence? For those arrangements, you'll have to multiple the percentage number with AWP to come up with a dollar amount to disclose for those type of negotiations.

**Comment by Ginger228** [comment]
> @Ginger228 Do you know what the AWP number is when building out these files on a monthly cadence? For those arrangements, you'll have to multiple the percentage number with AWP to come up with a dollar amount to disclose for those type of negotiations.

@shaselton-usds Using the AWP number isn't known until the date of service for the claim.  Per your instructions above, we would need to select the AWP on the date of the MRF build and apply the % to derive the negotiated rate.  In theory, this would be the incorrect value each month of reporting the fee for the infusion services that use AWP.

**Pull request merged**
