### PR TITLE
External references

### PR DESCRIPTION
**Pull request by shaselton-usds**
This PR addresses two issues:
* Adding the ability to refer to external in-network files to be combined together to make a valid in-network file
* Adding the ability to refer to external provider networks to be used in the in-network reporting

### CODE REVIEW

**Comment by shaselton-usds** [comment]
Tagging @tdfow @BobSyracuse @Devyandu @angelamarie0975 @taylorpatriciab due to previous engagement (sorry if I missed others).

There are a couple optional updates here. 

* You can now refer to [external provider groups](https://github.com/CMSgov/price-transparency-guide/blob/external-references/examples/provider-reference/provider-reference.json) (networks) defined in an external file [within the in-network file](https://github.com/CMSgov/price-transparency-guide/blob/external-references/examples/in-network-rates/in-network-rates-fee-for-service-single-plan-sample.json#L26-L27) to be [associated with negotiated items/services](https://github.com/CMSgov/price-transparency-guide/blob/external-references/examples/in-network-rates/in-network-rates-fee-for-service-single-plan-sample.json#L87).
* You can now [combine multiple in-network files](https://github.com/CMSgov/price-transparency-guide/blob/external-references/schemas/table-of-contents/table-of-contents.json#L30-L36) together to build a complete in-network file within the table of contents. Here is [an example](https://github.com/CMSgov/price-transparency-guide/blob/external-references/examples/table-of-contents/table-of-contents-sample.json#L16-L21) this is close to what was discussed previously.

Due to impact of these possible changes, I'll keep this PR open for a few days to let anyone drop thoughts they may have.

**Comment by Devyandu** [comment]
This is a very exciting (and long awaited) set of changes. Thanks !! 

Saw a couple of couple of minor issues and created pull requests for them.
I am curious how the tests passed since the TOC file example does not appear to be compliant with the schema. 

Still reviewing. Is it OK to create forks and pull requests like I did or do you prefer we report via comments on the pull request?

**Comment by taylorpatriciab** [comment]
@shaselton-usds Thank you so much!  This will significantly reduce the redundancy that was required prior to the update.

**Comment by Devyandu** [comment]
@shaselton-usds  I see that in_network_files is not a required element for a reporting_structure..
Your examples (and README) also have some plans which do not have any in_network_files. 

It is understood that the allowed_amount_file may not always be populated for a reporting_structure. 
But, what is the scenario where a reporting_structure object would not have in_network_files ?

**Comment by sharma-TIP** [comment]
Does that mean we can use one set of providers, rates and services which are common to say 100 plans . Then create a single JSON file for the common elements and reference that in the TOC. Or is this strictly for Rental network rates. Is there a limit of how many files can be references in the array.

**Comment by shaselton-usds** [comment]
@sharma-TIP No limit at this point. Yes, you can have those common files for items and services whose plans include them. 

Rental networks probably wouldn't be used in the Table of Contents file (mainly because it is information about providers and not negotiated items/service). The rental networks would most likely be used in the `provider_reference` attribute found in the in-network file.

**Comment by sharma-TIP** [comment]
> @sharma-TIP No limit at this point. Yes, you can have those common files for items and services whose plans include them.
> 
> Rental networks probably wouldn't be used in the Table of Contents file (mainly because it is information about providers and not negotiated items/service). The rental networks would most likely be used in the `provider_reference` attribute found in the in-network file.

Thank you so much. You are a life saver.

**Comment by oklanjsek** [comment]
> 

All these links are broken, can you please fix:
"...external provider groups (networks) defined in an external file within the in-network file to be associated with negotiated items/services.
You can now combine multiple in-network files ..."

**Pull request merged**
