### PR TITLE
Release

### PR DESCRIPTION
**Pull request by shaselton-usds**
The major pieces meant to address file size have been included in this release to master. This'll make the first "release" based on the latest tag created.

All of these changes should impact both the In-network and Allowed Amounts file.

* External in-network file references within the [table of contents file](https://github.com/CMSgov/price-transparency-guide/blob/release/examples/table-of-contents/table-of-contents-sample.json#L16-L22).
* External provider network file references within the [in-network file](https://github.com/CMSgov/price-transparency-guide/blob/release/examples/in-network-rates/in-network-rates-fee-for-service-single-plan-sample.json#L25-L28).
  *  An example [external provider network file](https://github.com/CMSgov/price-transparency-guide/blob/release/examples/provider-reference/provider-reference.json) to be referenced from within the in-network file.
* Added support for [billing code modifiers](https://github.com/CMSgov/price-transparency-guide/tree/release/schemas/in-network-rates#negotiated-price-object) ([example](https://github.com/CMSgov/price-transparency-guide/blob/release/examples/in-network-rates/in-network-rates-fee-for-service-single-plan-sample.json#L56)).
* Added support for [billing classes](https://github.com/CMSgov/price-transparency-guide/tree/release/schemas/in-network-rates#negotiated-price-object) ([professional/institutional example](https://github.com/CMSgov/price-transparency-guide/blob/release/examples/in-network-rates/in-network-rates-fee-for-service-single-plan-sample.json#L76))

### CODE REVIEW

**Comment by tdfow** [comment]
@shaselton-usds,  does the designation of a  'first release (current tag v0.10.1)' have any official meaning of a 'compliant' version of the schema for publication or does the first release just 'organize' the schema for references?  Will the true 'compliant version'  be noted/reference as v1.x.x (where x.x represents the latest version reference of v1)?   Assume CMS will identify when a tagged version is considered compliant for publication.  Is that true?

**Comment by shaselton-usds** [comment]
@tdfow The release has no official meaning. It is to organize the process of moving code into master formally starting now. 

The compliant version will start at v1.0.0. The release will be tagged as such too. 

Good questions.

**Comment by Nio-1** [comment]
The link above for the table of contents is broken.  Is the ToC embedded into the file in-network file or is the ToC its own separate file.  Please advise.

**Review by yosmirnjr — COMMENTED** [review]
Ápice

**Pull request merged**
