### PR TITLE
Updating to allow for reporting at the 10-digit HIOS level vs the 14-digit level

### PR DESCRIPTION
**Pull request by shaselton-usds**
Related discussion: https://github.com/CMSgov/price-transparency-guide/discussions/44

### CODE REVIEW

**Comment by Ginger228** [comment]
@shaselton-usds  Will the Schema be updated to show that the Plan ID for HIOS is 5 or 10 digits rather than 5 or 14?

**Comment by shaselton-usds** [comment]
@Ginger228 I don't believe the actual schema needs to be updated for this documentation change. 

Did you mean the examples? If so, good catch -- I'll do so.

**Comment by Ginger228** [comment]
> @Ginger228 I don't believe the actual schema needs to be updated for this documentation change.
> 
> Did you mean the examples? If so, good catch -- I'll do so.

Referring to this section
<html>
<body>


plan_id | Plan ID | String | The 14-digit Health Insurance Oversight System (HIOS) identifier, or, if the 14-digit HIOS identifier is not available, the 5-digit HIOS identifier, or if no HIOS identifier is available, the Employer Identification Number (EIN)for each plan or coverage offered by a plan or issuer. | No
-- | -- | -- | -- | --



</body>
</html>

**Comment by shaselton-usds** [comment]
@Ginger228 What section are you seeing that in? The Allowed Amounts, In-Network, and Table of Contents documentation has been updated in this PR.

**Comment by Ginger228** [comment]
> @Ginger228 What section are you seeing that in? The Allowed Amounts, In-Network, and Table of Contents documentation has been updated in this PR.

I still see it in the IN section.  I'll check tomorrow to see if it updates for me.  Thanks!

**Comment by shaselton-usds** [comment]
@Ginger228 Maybe you're looking at a different branch other than the `hios-documentation`. The changes are being introduced to the `develop` branch (and later to `master`).

Take a look for the changes here: https://github.com/CMSgov/price-transparency-guide/tree/hios-documentation/schemas/in-network-rates

**Comment by Ginger228** [comment]
> @Ginger228 Maybe you're looking at a different branch other than the `hios-documentation`. The changes are being introduced to the `develop` branch (and later to `master`).
> 
> Take a look for the changes here: https://github.com/CMSgov/price-transparency-guide/tree/hios-documentation/schemas/in-network-rates

You are correct.  So I'll see it on the main site tomorrow.  Thanks for helping!

**Comment by Paul-Sousa** [comment]
> No description provided.

@shaselton-usds what promoted this change?  We have been planning to use 14 digit HIOS so this would necessitate a change if those will no longer be valid.

Also, I assume this change won’t be needed for 7/1/22 as it is coming after v1.0 was finalized?

**Comment by tdfow** [comment]
@shaselton-usds  where is the source for the 10-digit reference coming from?   The mandate indicates (CMS-9915-F 235)...for example:  "The Departments did not receive any comments on this content element, and the final rules adopt this provision with modifications to ensure clarity of the expectations for reporting. As reflected in the updated regulatory text, the Departments are clarifying whether an EIN or HIOS ID is applicable for this element. Plans and issuers must include their HIOS ID at the 14-digit product level unless the plan or issuer does not have a HIOS ID at the plan or product level, in which case the plan or issuer must use the HIOS ID at the 5-digit issuer level. If a plan or issuer does not have a HIOS ID, it must use its EIN."   Where can we find the 'source' of this change for the 10-digit HIOS reference?

**Review by tdfow — COMMENTED** [review]
Why is 14 HIOS not valid, when the mandate has the 14 HIOS reference stated?   Please provide source for this change within the mandate.  As I only see the reference of 5 or 14 digit HIOS.  Where can I view the 10 digit HIOS requirement in the mandate?

**Comment by shaselton-usds** [comment]
@tdfow the 10-digit updates can be found [here in the PRA.](https://www.cms.gov/regulations-and-guidancelegislationpaperworkreductionactof1995pra-listing/cms-10715).

For v1.0, 14 or 5-digit can be used if you wish (meaning, it is still valid). If you wish to avoid reporting on the 14-digit level and would rather report on the 10-digit level, that is what this PR is. Depending on what version you choose to build the files against, you can either use the 14/5-digit (v1.0) or you can use the 10/5-digit (this version).

Actual documentation for why this was changed can be found in the [CMS-10715 - PRA Comments Responses.docx](https://www.reginfo.gov/public/do/DownloadDocument?objectID=116008200) document starting at the bottom of page 7. The page that it lives on is [here](https://www.reginfo.gov/public/do/PRAViewDocument?ref_nbr=202110-0938-016).

**Comment by Paul-Sousa** [comment]
> @tdfow the 10-digit updates can be found [here in the PRA.](https://www.cms.gov/regulations-and-guidancelegislationpaperworkreductionactof1995pra-listing/cms-10715)
> 
> For v1.0, 14 or 5-digit can be used if you wish (meaning, it is still valid). If you wish to avoid reporting on the 14-digit level and would rather report on the 10-digit level, that is what this PR is. Depending on what version you choose to build the files against, you can either use the 14/5-digit (v1.0) or you can use the 10/5-digit (this version).
> 
> Actual documentation for why this was changed can be found in the [CMS-10715 - PRA Comments Responses.docx](https://www.reginfo.gov/public/do/DownloadDocument?objectID=116008200) document starting at the bottom of page 7. The page that it lives on is [here](https://www.reginfo.gov/public/do/PRAViewDocument?ref_nbr=202110-0938-016).

@shaselton-usds based on that document, would it be more appropriate to allow either 14 digit or 10 digit?  As opposed to 14 digit no longer being valid?

**Comment by shaselton-usds** [comment]
@Paul-Sousa There is a hierarchy in the reporting requirement. Having an "or" removes the "if/then".

Are you finding that the component ID of the HIOS (the last 4 digits) to contain different negotiated rates across plans?

**Pull request merged**
