### PR TITLE
Table of contents

### PR DESCRIPTION
**Pull request by shaselton-usds**
Creating a table of contents (also known as an "index") file that captures plan information and the location on where the appropriate files for the plans can be downloaded.

This PR is addressing the file naming issue that can be found here: https://github.com/CMSgov/price-transparency-guide/discussions/260

For files that will include multiple plans, a table of contents file will be required with the following naming standard: `<YYYY-MM-DD>_<payer or issuer name>_index.<file extension>` . 

For files that only represent a single plan, the naming standard will be what it is currently: `<YYYY-MM-DD>_<payer or issuer name>_<plan name>_<file type name>.<file extension>`

As of right now, only a single in-network and allowed-amount file can be attached to a plan in the table of contents. There is flexibility in the schema to change this to support multiple in-network files that could be aggregated together to make a single in-network file, but as of right now, that isn't allowed. 

The goal here is to keep the PR to a single issue -- and this issue is to address file naming conventions.

### CODE REVIEW

**Comment by garysolebc** [comment]
Does it make sense to have an array of file references - one of the reasons I am suggesting this is because our networks are made up of an association of plans and thus each of those plans are generating a set of files that we currently need to merge together.  If we could have an array of references to each of our associations files that contain the providers that match the appropriate network.

**Comment by sharma-TIP** [comment]
> Does it make sense to have an array of file references - one of the reasons I am suggesting this is because our networks are made up of an association of plans and thus each of those plans are generating a set of files that we currently need to merge together. If we could have an array of references to each of our associations files that contain the providers that match the appropriate network.

Totally agree. This will split the files into manageable file sizes and data, and also reduce redundancy.

**Comment by tdfow** [comment]
@shaselton-usds will the reporting_plans array be removed from the allowed amount schema (https://github.com/CMSgov/price-transparency-guide/tree/table-of-contents/schemas/allowed-amounts)?   If I am understanding the table of contents approach, the reporting plans information will no longer be in the in-network or allowed amount schema and the TOC file schema would support the reporting plan array data.   Is that accurate?

**Comment by sharma-TIP** [comment]
> @shaselton-usds will the reporting_plans array be removed from the allowed amount readme documentation for the schema https://github.com/CMSgov/price-transparency-guide/tree/table-of-contents/schemas/allowed-amounts#:~:text=reporting_plans,Yes ; ? If I am understanding the table of contents approach, the reporting plans information will no longer be in the in-network or allowed amount schema and the TOC file schema would support the reporting plan array data. Is that accurate?

Then again ,even though TOC allows multiple plans to be reported in one file. Until two or more plans are exactly the same there is no difference. If the TOC will allow for a single plan to span over multiple files then it will make more sense/ make process much more manageable . 

For example a Plan A have 3 pricing arrangements; which is same as PLANB and PLANC . PLANB and PLANC have an additional pricing arrangement.  So in reality all three plans are different but 75% same. TOC does not allow to say partial information of PLANA, PLANB, PLANC in in a separate file and PLANB and PLANC information is in another file. Hope this makes sense.

**Comment by tdfow** [comment]
If the pricing is not the same, then it is my understanding that they must be reported uniquely.  It is my understanding that the TOC does not apply to the unique rate for only a single plan scenario.  I interpret the TOC for reporting multiple plans sharing the same rates, where you can group these scenarios for a given reporting entity.  
We do have situations where there are many plans with the same rates.  Since the TOC structure does have an array of reporting_structure, it does supports multiple in-network/allowed amount files to be grouped in one file for each set of reporting_plans for the reporting entity.  For example, if a reporting entity has multiple reporting_plans with 'same' rates, then the TOC would be used.  For example, the reporting entity has 100 plans with some 'same' rate scenarios:  50 plans that share the same rates (ie. fileA) and another set of 40 plans that have different rates than fileA but share the same rates reported in fileB and another set of 10 plans that have unique rates reported in fileC (different from fileA and fileB), then the TOC would contain the three reporting structures in the TOC.  The TOC will identify the 50 reporting_plans for fileA and the in-network/allowed amount data for those reporting_plans and then the 40 reporting_plans for fileB's to associate their in-network/allowed amount file data with fileB, and then 10 reporting_plans for fileC's in-network/allowed amount file data.  Is this in alignment with other's understanding?

**Comment by sharma-TIP** [comment]
> If the pricing is not the same, then it is my understanding that they must be reported uniquely. It is my understanding that the TOC does not apply to the unique rate for only a single plan scenario. I interpret the TOC for reporting multiple plans sharing the same rates, where you can group these scenarios for a given reporting entity. We do have situations where there are many plans with the same rates. Since the TOC structure does have an array of reporting_structure, it does supports multiple in-network/allowed amount files to be grouped in one file for each set of reporting_plans for the reporting entity. For example, if a reporting entity has multiple reporting_plans with 'same' rates, then the TOC would be used. For example, the reporting entity has 100 plans with some 'same' rate scenarios: 50 plans that share the same rates (ie. fileA) and another set of 40 plans that have different rates than fileA but share the same rates reported in fileB and another set of 10 plans that have unique rates reported in fileC (different from fileA and fileB), then the TOC would contain the three reporting structures in the TOC. The TOC will identify the 50 reporting_plans for fileA and the in-network/allowed amount data for those reporting_plans and then the 40 reporting_plans for fileB's to associate their in-network/allowed amount file data with fileB, and then 10 reporting_plans for fileC's in-network/allowed amount file data. Is this in alignment with other's understanding?

My understanding is one plan can be attached to one file. Maybe we need CMS to weigh in on this understanding . So from the example above although PLANA and PLANB share same rates they cannot be in different files( this is my understanding). Unless the PLANS are exactly the same then they cannot be combined.

**Comment by garysolebc** [comment]
Plans will typically share the same network and plans using that network, can be in the same file.  But we have many networks, so need a separate TOC file for each network or a different structure to allow for different plans to have different network references.  So agree a single _index does not work.  We would like to maybe have a network name, but will go with anything that allows us to have flexibility for many files.

**Comment by skochin** [comment]
Suggestion for the allowed-amounts and in-network-rates schemas to go along with the TOC: when the reporting entity is using a TOC file to point to these files, add an optional element like "plan_group_name" to give some description of which plans the file applies to.  

For example, 

   "reporting_entity_name": "Generic Health Plan",
   "reporting_entity_type": "health insurer",
   "plan_group_name": "HMO Plans"
   "last_updated_on": "2021/12/01",
   "version": "1.0.0",
 
You could also adopt a naming convention for these along the lines of  "2021-12-01_Generic-Health-Plan_HMO-Plans_in-network-rates.json"

**Comment by tdfow** [comment]
@garysolebc if a reporting entity has multiple networks, then why wouldn't the TOC be able to report the information in the same file--- as the rates for networkA are pointing to their unique rates and the rates for networkB are pointing to their unique rates
{
   "reporting_entity_name": "reporting entity name",
   "reporting_entity_type": "xxxxxxxxx",
   "reporting_structure": [{
     "reporting_plans": [{
       "plan_name": "plan A - networkA 1",
       "plan_id_type": "hios",
       "plan_id": "11111111111",
       "plan_market_type": "individual"
     },{
       "plan_name": "plan B - networkA 2",
       "plan_id_type": "hios",
       "plan_id": "0000000000",
       "plan_market_type": "individual"
     }],
     "in_network_file": {
       "description": "in-network file",
       "location": "https://www.some_site.com/files/in-network-file-123456**networkA**.json"
     },
     "allowed_amount_file": {
       "description": "allowed amount file",
       "location": "https://www.some_site.com/files/allowed-amount-file-123456**networkA**.json"
     }
  },{
     reporting_plans": [{
       "plan_name": "plan AB - networkB 1",
       "plan_id_type": "hios",
       "plan_id": "11111111111",
       "plan_market_type": "individual"
     },{
       "plan_name": "plan BC - networkB 2",
       "plan_id_type": "hios",
       "plan_id": "0000000000",
       "plan_market_type": "individual"
     }],
     "in_network_file": {
       "description": "in-network file",
       "location": "https://www.some_site.com/files/123**NetworkB**-in-network-file.json"
     },
     "allowed_amount_file": {
       "description": "allowed amount file",
       "location": "https://www.some_site.com/files/123**NetworkB**-allowed-amount-file.json"
     }
  }]
}

**Comment by sharma-TIP** [comment]
> 

@tdfow My understanding is on HIOS ID can be connected to one file "in_network_file" object, maybe my understanding is wrong. The way you described the structure above will definitely help.

**Comment by tdfow** [comment]
@sharma-TIP  the TOC schema has the reporting_plans array --so you can report multiple HIOS IDs IF they share the same rate information.  So the rates would be identified in one file, where the reporting_plans array would identify all the HIOS/EIN plans that share those same rates.
<html>
<body>


reporting_plans | In-Network Plans | Array | An array of reporting plan object types
-- | -- | -- | --



</body>
</html>

**Comment by sharma-TIP** [comment]
> @sharma-TIP the TOC schema has the reporting_plans array --so you can report multiple HIOS IDs IF they share the same rate information. So the rates would be identified in one file, where the reporting_plans array would identify all the HIOS/EIN plans that share those same rates.
> 
> reporting_plans	In-Network Plans	Array	An array of reporting plan object types

Thanks you , if that is the case then it will make things quite easy. @shaselton-usds , Would you confirm this assumption, please.

**Comment by shaselton-usds** [comment]
Thank you @tdfow for pointing out the outdated documentation in the allowed amounts README.md -- updated.

I think most of the comments here are pretty on-point in terms of understanding. 

First, the suggestion of allowing multiple files to be included that in aggregate make up the in-network/allowed amount files much like @garysolebc and @sharma-TIP were pointing out is out of scope for this particular PR, but it is well-noted. This PR is meant to solve the naming issues that arose when allowing multiple plans to point to a single file.  This was mentioned in the previous webinar -- we're looking to make this first iterative step with an eye to build on top of it. 

As of right now, for multiple plans to point to the same in-network/allowed amount file, they must have exactly the same negotiated rates for all of the items/service and their provider groups. Even if `Plan A` matches `Plan B` by 75%, they would each need to be reported in a separate file. 

The `table-of-contents` file allows for the grouping of multiple plans to point to a single in-network/allowed amounts file if those multiple plans are exactly the same RE: items/services, negotiated rates, and provider groups. You would group the similar 

The `table-of-contents` file can still contain information for unique plans at well that will require their own file by adding another `reporting_plan` object to the `reporting_plans` array.

In the following example:
* `Plan A` and `Plan B` have identical negotiated rates for all items/services for the **in-network** file. (in-network-file-1.json)
* `Plan C` is unique with its negotiated rates. (in-network-file-2.json)
* `Plan A` and `Plan C` both didn't meet the 20 claim threshold for any services for the **allowed amounts** file. (allowed-amounts-file-empty.json)
* `Plan B` met the 20 claim threshold for multiple services for the **allowed amounts** file. (allowed-amounts-file-1.json)
* `Plan A`, `Plan B`, and `Plan C` all have different HIOS numbers, they are different products.

```json
{
  "reporting_entity_name":"...",
  "reporting_entity_type":"...",
  "reporting_structure":[
    {
      "reporting_plans":[{
          "plan_name":"Plan A",
          "plan_id_type":"hios",
          "plan_id":"0000000000",
          "plan_market_type":"individual"
        },{
          "plan_name":"Plan B",
          "plan_id_type":"hios",
          "plan_id":"11111111111",
          "plan_market_type":"individual"
        }],
      "in_network_file":{
        "description":"in-network file",
        "location":"https://www.some_site.com/files/in-network-file-1.json"
      }
    },{
      "reporting_plans":[{
          "plan_name":"Plan C",
          "plan_id_type":"hios",
          "plan_id":"222222222",
          "plan_market_type":"individual"
        }],
      "in_network_file":{
        "description":"in-network file",
        "location":"https://www.some_site.com/files/in-network-file-2.json"
      },
      "allowed_amount_file":{
        "description":"allowed amount file",
        "location":"https://www.some_site.com/files/allowed-amounts-file-empty.json"
      }
    },{
      "reporting_plans":[
        {
          "plan_name":"Plan A",
          "plan_id_type":"hios",
          "plan_id":"0000000000",
          "plan_market_type":"individual"
        }],
      "allowed_amount_file":{
        "description":"allowed amount file",
        "location":"https://www.some_site.com/files/allowed-amounts-file-empty.json"
      }
    },{
      "reporting_plans":[
        {
          "plan_name":"Plan B",
          "plan_id_type":"hios",
          "plan_id":"11111111111",
          "plan_market_type":"individual"
        }],
      "allowed_amount_file":{
        "description":"allowed amount file",
        "location":"https://www.some_site.com/files/allowed-amounts-file-1.json"
      }
    }]
}
```

@sharma-TIP Did this clear up any questions that you had?

**Comment by sharma-TIP** [comment]
> Thank you @tdfow for pointing out the outdated documentation in the allowed amounts README.md -- updated.
> 
> I think most of the comments here are pretty on-point in terms of understanding.
> 
> First, the suggestion of allowing multiple files to be included that in aggregate make up the in-network/allowed amount files much like @garysolebc and @sharma-TIP were pointing out is out of scope for this particular PR, but it is well-noted. This PR is meant to solve the naming issues that arose when allowing multiple plans to point to a single file. This was mentioned in the previous webinar -- we're looking to make this first iterative step with an eye to build on top of it.
> 
> As of right now, for multiple plans to point to the same in-network/allowed amount file, they must have exactly the same negotiated rates for all of the items/service and their provider groups. Even if `Plan A` matches `Plan B` by 75%, they would each need to be reported in a separate file.
> 
> The `table-of-contents` file allows for the grouping of multiple plans to point to a single in-network/allowed amounts file if those multiple plans are exactly the same RE: items/services, negotiated rates, and provider groups. You would group the similar
> 
> The `table-of-contents` file can still contain information for unique plans at well that will require their own file by adding another `reporting_plan` object to the `reporting_plans` array.
> 
> In the following example:
> 
> * `Plan A` and `Plan B` have identical negotiated rates for all items/services for the **in-network** file. (in-network-file-1.json)
> * `Plan C` is unique with its negotiated rates. (in-network-file-2.json)
> * `Plan A` and `Plan C` both didn't meet the 20 claim threshold for any services for the **allowed amounts** file. (allowed-amounts-file-empty.json)
> * `Plan B` met the 20 claim threshold for multiple services for the **allowed amounts** file. (allowed-amounts-file-1.json)
> * `Plan A`, `Plan B`, and `Plan C` all have different HIOS numbers, they are different products.
> 
> ```json
> {
>   "reporting_entity_name":"...",
>   "reporting_entity_type":"...",
>   "reporting_structure":[
>     {
>       "reporting_plans":[{
>           "plan_name":"Plan A",
>           "plan_id_type":"hios",
>           "plan_id":"0000000000",
>           "plan_market_type":"individual"
>         },{
>           "plan_name":"Plan B",
>           "plan_id_type":"hios",
>           "plan_id":"11111111111",
>           "plan_market_type":"individual"
>         }],
>       "in_network_file":{
>         "description":"in-network file",
>         "location":"https://www.some_site.com/files/in-network-file-1.json"
>       }
>     },{
>       "reporting_plans":[{
>           "plan_name":"Plan C",
>           "plan_id_type":"hios",
>           "plan_id":"222222222",
>           "plan_market_type":"individual"
>         }],
>       "in_network_file":{
>         "description":"in-network file",
>         "location":"https://www.some_site.com/files/in-network-file-2.json"
>       },
>       "allowed_amount_file":{
>         "description":"allowed amount file",
>         "location":"https://www.some_site.com/files/allowed-amounts-file-empty.json"
>       }
>     },{
>       "reporting_plans":[
>         {
>           "plan_name":"Plan A",
>           "plan_id_type":"hios",
>           "plan_id":"0000000000",
>           "plan_market_type":"individual"
>         }],
>       "allowed_amount_file":{
>         "description":"allowed amount file",
>         "location":"https://www.some_site.com/files/allowed-amounts-file-empty.json"
>       }
>     },{
>       "reporting_plans":[
>         {
>           "plan_name":"Plan B",
>           "plan_id_type":"hios",
>           "plan_id":"11111111111",
>           "plan_market_type":"individual"
>         }],
>       "allowed_amount_file":{
>         "description":"allowed amount file",
>         "location":"https://www.some_site.com/files/allowed-amounts-file-1.json"
>       }
>     }]
> }
> ```
> 
> @sharma-TIP Did this clear up any questions that you had?

Thanks @shaselton-usds this clears it up. 

Each time there is a change in the grouping it takes a lot of adjustment to our ,code base, and we have to kind of go to the drawing board to redesign/reinvestigate the complete process. It takes time and effort to incorporate a change ( due to the large amount of data that needs to be joined to produce the said schema) , and by the time we are close to make a workable solution something changes in the schema. I understand that this is an iterative process driven through suggestions from everyone on what works the best. If there an extension of time-line on horizon? 

Coming back to the TOC; We were hoping that the following example could be incorporated in the schema , it will bring down the file size’s considerably and remove redundancy between the files. 
In the following example PLANA and PLANB are partially similar:
Plan A – Network 1 
Plan B – Network 1 and Network 2. 
Plan C – Network 3 
Network define same services, Provider groups/ Rates
Taking just allowed In-Network example

{
  "reporting_entity_name":"...",
  "reporting_entity_type":"...",
  "reporting_structure":[
    {
      "reporting_plans":[{
          "plan_name":"Plan A",
          "plan_id_type":"hios",
          "plan_id":"0000000000",
          "plan_market_type":"individual"
        },{
          "plan_name":"Plan B",
          "plan_id_type":"hios",
          "plan_id":"11111111111",
          "plan_market_type":"individual"
        }],
      "in_network_file":{
        "description":"in-network file",
        "location":"https://www.some_site.com/files/Network1-file-1.json"
      }
    },

   {
      "reporting_plans”:{
          "plan_name":"Plan B",
          "plan_id_type":"hios",
          "plan_id":"11111111111",
          "plan_market_type":"individual"
        }],
      "in_network_file":{
        "description":"in-network file",
        "location":"https://www.some_site.com/files/Network2-file-1.json"
      }
    },
    {
      "reporting_plans”:{
          "plan_name":"Plan C",
          "plan_id_type":"hios",
          "plan_id":"22222222222",
          "plan_market_type":"individual"
        }],
      "in_network_file":{
        "description":"in-network file",
        "location":"https://www.some_site.com/files/Network3-file-1.json"
      }
    },

**Comment by garysolebc** [comment]
@tdfow 
> @garysolebc if a reporting entity has multiple networks, then why wouldn't the TOC be able to report the information in the same file--- as the rates for networkA are pointing to their unique rates and the rates for networkB are pointing to their unique rates... see above for code example...
> 
> @shaselton-usds can you confirm if my understanding is correct?

Our plan partners are all in different parts of the country, and all making their own INN files for their business.  We each hold a portion of the total network - typically geographical.  So our providers in our geographic area have a relationship with us, and providers in a different state have a relationship with a partner.  From our member perspective though they have one network with us.  If our member goes to a provider say in California, they are still considered to be in our network although we don't have a direct relationship with that provider.  Our current plan is for all our shared partners across the country to share our INN files and in essence make a lot of duplicated copies of the same file that represents all the providers in the country.  Our own file is currently sitting at 11GB - we will then multiply that by combining the rest of the plans and have a single network file of over 300GB - this is before some of the more recent changes.  My ask is that instead of us having to send and make a whole lot of copies of the same 300GB file, that we can reference our partners file as they pertain to our member network.  So, what I would like is simply:

...
"reporting_plans": [{
"plan_name": "plan A - networkA 1",
"plan_id_type": "hios",
"plan_id": "11111111111",
"plan_market_type": "individual"
},{
"plan_name": "plan B - networkA 2",
"plan_id_type": "hios",
"plan_id": "0000000000",
"plan_market_type": "individual"
}],
"in_network_file": {
"description": "in-network file",
"locations": [ { "location": "https://www.partnerA_site.com/files/in-network-file-123456networkA.json" },
                     { "location": "https://www.partnerB_site.com/files/in-network-file-4564networkA.json" },
                     { "location": "https://www.partnerC_site.com/files/in-network-file-988networkA.json" },
]
},
...

This type of approach would also allow for each partner to manage their files as they see fit, thus we could even split our network files up differently so that we can manage them better over time.  I think splitting out the provider data like you are planning is great as the data that likely changes the most from month to month is provider information and the rates change much more slowly.  But if we had the ability to point to files in a different month that we could identify did not actually change that month may be beneficial too.

**Comment by shaselton-usds** [comment]
@sharma-TIP Understood that iterative changes to the schema may require rework -- these recent changes have been optional. You do not need to include them if you find it too difficult to incorporate them or don't find them necessary. Most of these changes have been to address the community's feedback based on use-cases.

@sharma-TIP @garysolebc It has been mentioned a couple of times but there isn't the concept of splitting up files at this moment. This PR is only to solve the naming issue that came about by allowing multiple plans use the same in-network/allowed amount files if those plans pass the necessary requirements. We are still looking into this possibility though.

**Comment by sharma-TIP** [comment]
> @sharma-TIP Understood that iterative changes to the schema may require rework -- these recent changes have been optional. You do not need to include them if you find it too difficult to incorporate them or don't find them necessary. Most of these changes have been to address the community's feedback based on use-cases.
> 
> @sharma-TIP @garysolebc It has been mentioned a couple of times but there isn't the concept of splitting up files at this moment. This PR is only to solve the naming issue that came about by allowing multiple plans use the same in-network/allowed amount files if those plans pass the necessary requirements. We are still looking into this possibility though.

Thank you .

**Comment by tdfow** [comment]
@shaselton-usds  I think there is still some clean up needed in the in-network schema for the table of contents change---as I am still seeing reporting_plans (ie.  https://github.com/CMSgov/price-transparency-guide/blob/table-of-contents/schemas/in-network-rates/in-network-rates.json) 
If reporting_plans is being moved to TOC, then it wouldn't be in the in-network schema.

 "reporting_plans": {
      "type": "object",
      "properties": {
      },
      "required": [
        "plan_name",
        "plan_id_type",
        "plan_id",
        "plan_market_type"
      ]
    }
  },

**Comment by Kvillafor** [comment]
Will the optional TOC be added and published for both schemas?

**Comment by tdfow** [comment]
Since the proposal for Table of Contents has impact on the schema for In-Network and Allowed Amount---when can we expect whether or not this change is proceeding or not?  @shaselton-usds , any CMS timeline for this?

**Comment by shaselton-usds** [comment]
Thank you all for your patience. Once in develop, I'll push this into the master branch.

**Comment by tdfow** [comment]
@shaselton-usds  Should the multi-plan example be applicable for the Allowed Amount MRF too?

**Pull request merged**
